# Generated by Django 4.2.28 on 2026-02-19 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('time_spent_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('was_correct', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='decks.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateField(default=datetime.date.today)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('NEW', 'Nova'), ('LEARNING', 'Aprendendo'), ('REVIEW', 'Revisão')], default='NEW', max_length=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='decks.card')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
    ]
