# Generated by Django 4.2.28 on 2026-02-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cards_per_day', models.PositiveIntegerField(default=20)),
                ('max_reviews_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('session_order', models.CharField(choices=[('reviews_first', 'Revisões primeiro'), ('new_first', 'Novas primeiro')], default='reviews_first', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
