# Generated by Django 4.2.28 on 2026-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='back_language',
            field=models.CharField(choices=[('pt-BR', '🇧🇷 Português (Brasil)'), ('en-US', '🇺🇸 English (US)'), ('en-GB', '🇬🇧 English (UK)'), ('es-ES', '🇪🇸 Español'), ('fr-FR', '🇫🇷 Français'), ('de-DE', '🇩🇪 Deutsch'), ('it-IT', '🇮🇹 Italiano'), ('ja-JP', '🇯🇵 日本語'), ('zh-CN', '🇨🇳 中文'), ('ko-KR', '🇰🇷 한국어')], default='pt-BR', max_length=10, verbose_name='Idioma do verso (pronúncia)'),
        ),
        migrations.AddField(
            model_name='deck',
            name='front_language',
            field=models.CharField(choices=[('pt-BR', '🇧🇷 Português (Brasil)'), ('en-US', '🇺🇸 English (US)'), ('en-GB', '🇬🇧 English (UK)'), ('es-ES', '🇪🇸 Español'), ('fr-FR', '🇫🇷 Français'), ('de-DE', '🇩🇪 Deutsch'), ('it-IT', '🇮🇹 Italiano'), ('ja-JP', '🇯🇵 日本語'), ('zh-CN', '🇨🇳 中文'), ('ko-KR', '🇰🇷 한국어')], default='en-US', max_length=10, verbose_name='Idioma da frente (pronúncia)'),
        ),
    ]
