# Generated by Django 4.2.28 on 2026-02-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_back_language_deck_front_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('cloze', 'Cloze (lacuna)')], default='normal', max_length=10, verbose_name='Tipo do card'),
        ),
    ]
